---
title: "Repère de l'espace"
format:
  html:
    toc: true
    number-sections: false
description: "Coordonnées d'un point, coordonnées de vecteurs"
order: 3
---



### Notion de repère et coordonnées

::: {.bloc .def}
<span class="bloc-titre">Définition : </span>

On appelle **base de l'espace** tout triplet $\left(\ve{i},\ve{j},\ve{k}\right)$ de vecteurs non coplanaires de $\vE$.  
On appelle **repère de l'espace**, la donnée d'un quadruplet $\left(O \, ; \, \ve{i},\ve{j},\ve{k}\right)$ où $O$ est un point de $\E$ appelé origine du repère et $\left(\ve{i},\ve{j},\ve{k}\right)$ une base de l'espace.
:::



::: {.bloc .thm}
<span class="bloc-titre">Théorème : </span>

On considère $\left(O \, ; \, \ve{i},\ve{j},\ve{k}\right)$ un repère de l'espace.  
Pour tout point $M$ de l'espace, il existe un unique triplet $(x \, ; \, y \, ; \, z)$ de réels tel que : 
$$\ve{OM}=x\ve{i}+y\ve{j}+z\ve{k}$$

1. On dit alors que $M$ a pour coordonnées $(x,y,z)$ où $x$ est l'**abscisse** de $M$, $y$ son **ordonnée** et $z$ sa **cote**.
2. Pour tout $\ve{u} \in \vE$ tel que $\ve{u}=\ve{OM}$, on a $\ve{u}=x\ve{i}+y\ve{j}+z\ve{k}$. On note alors $\ve{u}\begin{pmatrix}x\\y\\z\end{pmatrix}$ ou $\ve{u}(x \, ; \, y \, ; \, z)$.
:::

<details class="bloc demo">
<summary>Démonstration : </summary>

Soit $\ve{w}$ un vecteur de l'espace, $O$ un point de l'espace et $M$ le point de l'espace tel que $\ve{w}=\ve{OM}$. On note $M'$ le projeté de $M$ sur le plan $\left(O \, ; \, \ve{i},\ve{j}\right)$ parallèlement à la droite $\left(O \, ; \, \ve{k}\right)$.  
On a alors, par la relation de Chasles : 
$$\ve{OM}=\ve{OM'}+\ve{M'M}$$

* $\ve{M'M}$ est colinéaire à $\ve{k}$, donc il existe un réel $z$ tel que $\ve{M'M}=z\ve{k}$.
* Comme $M' \in \left(O \, ; \, \ve{i},\ve{j}\right)$, il existe deux réels $x$ et $y$ tels que $\ve{OM'}=x\ve{i}+y\ve{j}$.

D'où le résultat : $\ve{OM}=x\ve{i}+y\ve{j}+z\ve{k}$. L'unicité du triplet est une conséquence de l'unicité du point $M$ et de la non-coplanarité des vecteurs de base.

</details>



::: {.bloc .rem}
<span class="bloc-titre">Remarque : </span>

Il existe d'autres types de coordonnées, comme par exemple les coordonnées sphériques (celles utilisées pour repérer un point sur Terre).
:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple :</div>

On considère un cube $ABCDEFGH$.

1. Justifier que $\left(\ve{AB},\ve{AE},\ve{AD}\right)$ est une base de l'espace.

<details class="bloc cor"><summary>Afficher la correction :</summary>
Les trois vecteurs $\ve{AB}$, $\ve{AE}$ et $\ve{AD}$ ne sont pas coplanaires (ils suivent les trois dimensions du cube), ils forment donc une base de l’espace.
</details>


2. Déterminer les coordonnées des vecteurs $\ve{AH}$ et $\ve{AG}$ dans le repère $(A \, ; \, \ve{AB}, \ve{AE}, \ve{AD})$.

<details class="bloc cor"><summary>Afficher la correction :</summary>
Dans le repère $\left(A \, ; \, \ve{AB},\ve{AE},\ve{AD}\right)$ :

  * Par décomposition : $\ve{AH} = \ve{AD} + \ve{DH}$. Comme $ABCDEFGH$ est un cube, $\ve{DH} = \ve{AE}$.
  * Donc $\ve{AH} = 0\ve{AB} + 1\ve{AE} + 1\ve{AD}$. Le vecteur $\ve{AH}$ a pour coordonnées $(0,1,1)$.
  * De même, $\ve{AG} = \ve{AB} + \ve{BC} + \ve{CG} = \ve{AB} + \ve{AD} + \ve{AE}$. Le vecteur $\ve{AG}$ a pour coordonnées $(1,1,1)$.

</details>

:::

---

### Calculs et coordonnées
::: {.bloc .thm}
<span class="bloc-titre">Théorème : </span>

Soit $\left(O \, ; \, \ve{i},\ve{j},\ve{k}\right)$ un repère de l'espace.  
On considère $A(x_A,y_A,z_A)$ et $B(x_B,y_B,z_B)$ deux points de $\E$, $\ve{u}\begin{pmatrix}x\\y\\z\end{pmatrix}$ et $\ve{v}\begin{pmatrix}x'\\y'\\z'\end{pmatrix}$ deux vecteurs de $\vE$ et $k \in \mathbb{R}$.  
Alors :

$$\ve{AB}\begin{pmatrix}x_B-x_A\\y_B-y_A\\z_B-z_A\end{pmatrix} \qquad \ve{u}+\ve{v}\begin{pmatrix}x+x'\\y+y'\\z+z'\end{pmatrix} \qquad k\ve{u}\begin{pmatrix}kx\\ky\\kz\end{pmatrix}$$
:::

<details class="bloc demo">
<summary>Démonstration : </summary>

Les démonstrations sont immédiates et reposent uniquement sur la définition des coordonnées d'un point et d'un vecteur dans un repère ainsi que sur la relation de Chasles pour le vecteur $\ve{AB}$.

</details>

::: {.bloc .ex}
<div class="bloc-titre">Exemple 1 :</div>

Soit $\left(O \, ; \, \ve{i},\ve{j},\ve{k}\right)$ un repère de l'espace et $A(2,-5,3)$, $B(-1,3,1)$ deux points de l'espace.

1. Déterminer les coordonnées de $\ve{AB}$.
<details class="bloc cor"><summary>Afficher la correction :</summary>
$\ve{AB}\begin{pmatrix}
-1-2\\
3-(-5)\\
1-3
\end{pmatrix}
= \begin{pmatrix}
-3\\8\\-2
\end{pmatrix}$
</details>


2. Déterminer les coordonnées de $C$ vérifiant $\ve{AC}=2\ve{CB}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>
On a 
$$\left\{\begin{array}{l}
x_C-2=2(-1-x_C)\\
y_C-(-5)=2(3-y_C)\\
z_C-3=2(1-z_C)
\end{array}\right.
\Longleftrightarrow
\left\{\begin{array}{l}
x_C=0\\
y_C=\frac{1}{3}\\
z_C=\frac{5}{3}
\end{array}\right.$$

Donc $C\left(0\,;\,\frac{1}{3}\,;\,\frac{5}{3}\right)$

</details>
:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple  :</div>

On considère $\ve{u}\begin{pmatrix}1\\1\\1\end{pmatrix}$, $\ve{v}\begin{pmatrix}-1\\1\\0\end{pmatrix}$ et $\ve{w}\begin{pmatrix}1\\0\\1\end{pmatrix}$.  
Montrer que ces vecteurs ne sont pas coplanaires.

<details class="bloc cor"><summary>Afficher la correction :</summary>
On considère $a,b,c \in \R$ tels que $a\ve{u}+b\ve{v}+c\ve{w}=\ve{0}$.

$$a\ve{u}+b\ve{v}+c\ve{w}=\ve{0}\Longleftrightarrow
\left\{\begin{array}{l}
a-b+c=0\\
a+b=0\\
a+c=0
\end{array}\right.
\Longleftrightarrow
\left\{\begin{array}{l}
a=0\\
b=0\\
c=0
\end{array}\right.$$

On déduit alors que les trois vecteurs sont linéairement indépendants. Ils forment donc une base de l'espace.

</details>
:::



<div class="nav-pages">
  <a class="prev" href="vecteur_espace.html">⬅️</a>
  <a class="next" href="droite_plan.html">➡️</a>
</div>
