---
title: "La recurrence"
format:
  html:
    toc: true
    number-sections: false
description: "Principe de récurrence et application à l'étude des suites"
order: 2
---



-----


## Axiomatisation des entiers naturels

::: {.bloc .thm}
<span class="bloc-titre">Axiomes de Peano :</span>  
La définition axiomatique des entiers naturels de Peano peut être décrite par les cinq axiomes :

1. L'élément appelé zéro et noté $0$ est un entier naturel.  
2. Tout entier naturel $n$ a un unique successeur, noté $s(n)$ ou $S(n)$ qui est un entier naturel.  
3. Aucun entier naturel n'a $0$ pour successeur.  
4. Deux entiers naturels ayant le même successeur sont égaux.  
5. (Axiome de récurrence) Si un ensemble d'entiers naturels contient $0$ et contient le successeur de chacun de ses éléments, alors cet ensemble contient $\N$.  
:::

---

## Principe du raisonnement

::: {.bloc .rem}
On souhaite démontrer une propriété qui dépend de $n$, où $n \in \N$.  
Pour cela, on peut utiliser le raisonnement par récurrence (ou par induction).  
Il se décompose en trois étapes :

**Initialisation – Hérédité – Conclusion**

1. **Initialisation :**  
   C'est l'étape où l'on prouve que la proposition est vraie au départ (au rang $n_0$).  
   Il faut donc démontrer : $P_{n_0}$ vraie.

2. **Hérédité :**  
   On suppose que pour un entier $n$, $P_n$ est vrai, et on montre que $(P_n \Rightarrow P_{n+1})$ est vraie. 
    
   On déduit alors, de la table de vérité de l'implication, que $P_{n+1}$ est aussi vraie. 

   On dit alors que la propriété est **héréditaire**.

3. **Conclusion :**  
   On a $P_0$ et $\forall \, k \in \N, \, (P_k \Longrightarrow P_{k+1})$ vraie (il s'agit de l’hérédité).  
   On déduit que $\forall \, n \in \N, \, P_n$ est vraie.
:::


::: {.bloc .rem}
**Comprendre le raisonnement :**

Ainsi, on a :  

- $(P_0 \Longrightarrow P_1)$ et $P_0$ vraie, donc $P_1$ est vraie ;  
- $(P_1 \Longrightarrow P_2)$ et $P_1$ vraie, donc $P_2$ est vraie ;  
- $\cdots$ ;  
- $(P_n \Longrightarrow P_{n+1})$ et $P_n$ vraie, donc $P_{n+1}$ est vraie ;  
- $\cdots$ ;  

On a donc, pour tout entier naturel $n$, $P_n$ vraie.



Une manière facile de visualiser un raisonnement par récurrence consiste à faire l'analogie avec le jeu de la chute en cascade des dominos (une infinité !) :  

- La chute du premier domino constitue l'initialisation ;  
- « Si un domino tombe, alors le suivant tombe » constitue l'hérédité ;  
- La chute en cascade de l'ensemble de la structure est la conclusion.  
:::


---

::: {.bloc .ex}
<span class="bloc-titre">Exemples : </span><br>

Démontrons que, pour tout entier naturel $n$ non nul, la somme des $n$ premiers entiers impairs est $n^2$.  
C'est-à-dire que pour tout $n \in \N^*$,

$$
S_n = \sum_{k=0}^{n-1} (2k+1) = (2 \times 0 + 1) + (2 \times 1 + 1) + (2 \times 2 + 1) + \dots + (2(n-1) + 1) = n^2.
$$

<details class="bloc cor"><summary>Afficher la correction</summary>

Soit, pour tout entier $n$ non nul, $P_n : S_n = n^2$.

- *Initialisation :*  
  Pour $n=1$, $1^2 = 1$, et $S_1 = 2 \times 0 + 1 = 1$.  
  Ainsi, $P_1$ est vraie, et la récurrence est initialisée.

- *Hérédité :*  
  On suppose que pour un entier $n \geqslant 1$ arbitrairement fixé, la propriété $P_n$ est vraie.  
  Démontrons que $(P_n \Rightarrow P_{n+1})$ est vraie.  

  $$
  \sum_{k=0}^{n} (2k+1) = \underbrace{(2 \times 0 + 1) + (2 \times 1 + 1) + (2 \times 2 + 1) + \dots + (2(n-1) + 1)}_{S_n = n^2} + (2n + 1)
  $$

  $$
  = n^2 + 2n + 1 = (n+1)^2.
  $$

  On a $P_n$ vraie et la propriété est héréditaire, donc $P_{n+1}$ est vraie.

- *Conclusion :*  
  On a $P_1$ et $\forall \, n \in \N^*, \, (P_n \Rightarrow P_{n+1})$ vraie.  
  On déduit que $\forall \, n \in \N^*, \, P_n$ est vraie.

</details>
:::


::: {.bloc .ex}
<span class="bloc-titre">Exemples : </span><br>

Soit $u$ une fonction définie et dérivable sur $I$.  
Démontrons que pour tout entier naturel $n$ non nul, $u^n$ est dérivable et $(u^n)' = n u' u^{n-1}$.

<details class="bloc cor"><summary>Afficher la correction</summary>

On note, pour tout entier naturel $n$ non nul, $P_n$ : « $u^n$ est dérivable et $(u^n)' = n u' u^{n-1}$ ».

- *Initialisation :*  
  Pour $n=1$, $(u^1)' = u'$ et $n u' u^{n-1} = 1 \times u' \times u^0 = u'$.  
  Ainsi, $P_1$ est vraie.

- *Hérédité :*  
  On suppose que pour un entier $n \geqslant 1$ arbitrairement fixé, la propriété $P_n$ est vraie, c'est-à-dire que $u^n$ est dérivable et $(u^n)' = n u' u^{n-1}$.  
  Démontrons que $(P_n \Rightarrow P_{n+1})$ est vraie.  

  $u^{n+1} = u \times u^n$, ainsi $u^{n+1}$ est dérivable comme produit de fonctions dérivables.  

  Or,  

  $$
  (u^{n+1})' = (u \times u^n)' = u' u^n + u \times n u' u^{n-1} = u' u^n + n u' u^n = (n+1) u' u^n.
  $$

  On déduit alors que $(P_n \Rightarrow P_{n+1})$ est vraie.  
  Ainsi, $P_n$ est vraie et la propriété est héréditaire, donc $P_{n+1}$ est vraie.

- *Conclusion :*  
  On a $P_1$ et $\forall \, n \in \N^*, \, (P_n \Rightarrow P_{n+1})$ vraie.  
  On déduit que $\forall \, n \in \N^*, \, P_n$ est vraie, donc $u^n$ est dérivable et $(u^n)' = n u' u^{n-1}$.

</details>
:::




<div class="nav-pages">
  <a class="prev" href="historique.html">⬅️</a>
  <a class="next" href="application.html">➡️</a>
</div>
