---
title: "Equations trigonométriques"
format:
  html:
    toc: true
    number-sections: false
description: "Résolution d'équations trigonométriques"
order: 5
---

::: {.bloc .thm}
<span class="bloc-titre">Théorème : </span><br>
Soit $t$ et $a$ deux réels, alors :<br>
$$\cos t=\cos a \Longleftrightarrow t = a + 2k\pi~~~\text{ou}~~~t=-a + 2k\pi~~,~~k \in \Z$$
$$\sin t=\sin a \Longleftrightarrow t = a + 2k\pi~~~\text{ou}~~~t= \pi-a + 2k\pi~~,~~k \in \Z$$
:::

<details class="bloc demo"><summary>Démonstration : </summary>
Cela découle de la propriété 2
</details>

::: {.bloc .ex}
<span class="bloc-titre">Exemple : </span><br>
Résoudre dans $I = \left]-\frac{13 \pi}{3}~~;~\frac{11 \pi}{3} \right]$ l'équation $\cos t = \frac{1}{2}$<br>
<details class="bloc cor"><summary>Afficher la correction</summary>

$\forall t  \in \R, \, \cos t = \cos \frac{\pi}{3} \Longleftrightarrow \left\{\begin{array}{l}
t = \frac{\pi}{3} + 2k\pi\\
t=-\frac{\pi}{3} + 2k\pi
\end{array} \right.~~ k \in \Z$

- On a pour tout $k \in \Z$,  
  $$
  -\frac{13\pi}{3} < \frac{\pi}{3} + 2k \pi \leqslant \frac{11\pi}{3} \Leftrightarrow
  -\frac{14}{3} < 2k \leqslant \frac{10}{3}
  \Leftrightarrow
  -\frac{14}{6} < k \leqslant \frac{10}{6}
  $$
  Ainsi $ k \in \{-2 \, ;\, -1 \, ;\,  0 \, ;\,  1\}$.<br>
  Les solutions sont alors $S_1=\left\{-\frac{11\pi}{3} \, ; \, -\frac{5\pi}{3} \, ;\,-\frac{\pi}{3} \, ; \, \frac{7\pi}{3}  \right\}$

- On a pour tout $k \in \Z$, 
  $$
  -\frac{13\pi}{3} < -\frac{\pi}{3} + 2k' \pi \leqslant \frac{11\pi}{3}  
  \Leftrightarrow
  -\frac{12}{3} < 2k' \leqslant \frac{12}{3}
  \Leftrightarrow
  -\frac{12}{6} < k' \leqslant \frac{12}{6}
  $$
  Ainsi $ k' \in \{ -1 \, ;\,  0 \, ;\,  1 \, , \, 2\}$.<br>
  Les solutions sont alors $S_2=\{-\frac{7\pi}{3} \, ; \, -\frac{\pi}{3} \, ;\, \frac{5\pi}{3} \, ; \, \frac{11\pi}{3}  \}$

Ainsi l'équation admet comme solutions :<br>
$$S = \left\{-\frac{11\pi}{3}~;~~-\frac{7\pi}{3}~~;~-\frac{5\pi}{3}~;~-\frac{\pi}{3}~;~\frac{\pi}{3}~;~\frac{5\pi}{3}~;~\frac{7\pi}{3}~;~\frac{11\pi}{3} \right\}$$
</details>
:::

::: {.bloc .ex}
<span class="bloc-titre">Exemple : </span><br>
Soient deux réels $$a=\frac{1}{2}\sqrt{2+\sqrt{2}} \quad et \quad b=\frac{1}{2} \sqrt{2-\sqrt{2}}$$

1. a) Résoudre sur $\R$ puis sur $]-\pi \, ;\, \pi]$, éventuellement à l'aide du cercle trigonométrique, l'équation $(E) : \, \cos 4x = 0$.<br>
   <details class="bloc cor"><summary>Afficher la correction</summary>
   Résolution algébrique :<br>
   $$\cos 4 x = 0\Longleftrightarrow \cos 4x = \cos \frac{\pi}{2} \Longleftrightarrow
        \left\{\begin{array}{l}
        4x= \frac{\pi}{2} +2k \pi\\
        \text{ou}\\
        4x=-\frac{\pi}{2} + 2k\pi
      \end{array} \right. , \, k \in \Z
        \Longleftrightarrow
        \left\{\begin{array}{l}
        x= \frac{\pi}{8} +k \frac{\pi}{2}\\
        \text{ou}\\
        x=-\frac{\pi}{8} + k \frac{\pi}{2}
      \end{array} \right. , \, k \in \Z$$
   Ainsi $$S_{\R} = \left\{-\frac{\pi}{8} + k \frac{\pi}{2}, \, k \in \Z \right\} \cup \left\{ \frac{\pi}{8} + k \frac{\pi}{2}\, , \, k \in \Z\right\}$$
   et $$S_{]-\pi \, ; \, \pi]} =\left\{-\frac{7\pi}{8} \, ;\,-\frac{5\pi}{8} \, ;\, -\frac{3\pi}{8} \, ;\, -\frac{\pi}{8} \, ;\, \frac{\pi}{8} \, ;\, \frac{3\pi}{8} \, ;\, \frac{5\pi}{8} \, ;\, \frac{7\pi}{8} \right\}$$
   </details>

   b) Représenter les solutions sur le cercle trigonométrique.

On admet que pour tout réel , $$\cos 4x = 8\cos^4x -8 \cos^2x +1$$


2. a) On effectue le changement de variable $X=\cos^2 x$.<br>
   $$
   8X^2-8X +1=0
   $$ 
   Résoudre cette dernière équation <br>
   <details class="bloc cor"><summary>Afficher la correction</summary>
   $\Delta= (-8)^2- 4 \times 8 \times 1 = 32 >0$.<br>
   Le discriminant étant positif, le polynôme $8X^2-8X +1$ admet deux racines réelles distinctes : <br>
   $$X_1 = \frac{2+\sqrt{2}}2 \quad \text{ et } \quad X_2 = \frac{2-\sqrt{2}}2$$
   </details>

   b) Déterminer les valeurs de $\cos x $, où $x$ est solution de l'équation $(E)$.<br>
   <details class="bloc cor"><summary>Afficher la correction</summary>
   Pour tout réel $x$, 
   $$\cos 4x = 0 \Longleftrightarrow 8\cos^4x -8 \cos^2x +1  = 0 \Longleftrightarrow 
   \left\{\begin{array}{l} 
   \cos^2  x= X\\
   8X^2-8X+1 = 0 
   \end{array} \right. 
   \Longleftrightarrow
   \left\{\begin{array}{l}
   X= \cos^2 x \\
   X= \frac{2+\sqrt{2}}2 \text{ ou } X = \frac{2-\sqrt{2}}2 
   \end{array} \right.$$
   On déduit alors que les valeurs de $\cos x$ sont <br>
   $$S= \left\{\sqrt{\frac{2-\sqrt{2}}2} \, ; \, -\sqrt{\frac{2-\sqrt{2}}2} \, ; \, - \sqrt{\frac{2+\sqrt{2}}2} \, ; \, \sqrt{\frac{2+\sqrt{2}}2} \right\}$$
   </details>

   c) En déduire que $\cos \frac{\pi}{8} =a$ et $\cos \frac{3\pi}{8} =b$<br>
   <details class="bloc cor"><summary>Afficher la correction</summary>
   Soit $\alpha = \frac{\pi}8$ et $\beta= \frac{3\pi}8$. Alors $\cos 4 \alpha = 0$  et $\cos 4 \beta=0$.<br>
   Donc $\cos \alpha \in S$ et $\cos \beta \in S$.<br>
   De plus $\alpha , \beta\in \left[0 \, ; \ \frac{\pi}2 \right[$ donc $\cos \alpha >0$ et $\cos \beta >0$.<br>
   Ainsi $$\cos \alpha , \cos \beta \in \left\{\sqrt{\frac{2-\sqrt{2}}2} \, ; \, \sqrt{\frac{2+\sqrt{2}}2} \right\}$$
   Or $\cos$ est décroissante sur $\left[0 \, ; \ \frac{\pi}2 \right[$.<br>
   Donc $$\alpha  < \beta \Longrightarrow \cos \alpha  > \cos \beta$$
   On déduit alors que <br>
   $$\cos \alpha = \sqrt{\frac{2+\sqrt{2}}2} \quad \text{ et } \quad \cos \beta = \sqrt{\frac{2-\sqrt{2}}2}$$
   </details>
:::

<div class="nav-pages">
  <a class="prev" href="lignes_trigo.html">⬅️</a>
</div>
