---
title: "Composition : g(ax+b)"
description: "Intervalle image - composée de fonctions - dérivée de la composée"
format:
  html:
    toc: true
    number-sections: false
order: 2
---

### Dérivée de $g(ax+b)$

::: {.bloc .def}
<span class="bloc-titre">Définition : </span><br>
Soit $f$ une fonction définie sur $I$.<br>
On appelle \emph{intervalle image} de $I$ par $f$ l'ensemble noté $f(I)$ défini par

$$
f(I) = \left\{\,f(x)\; ;\; x \in I \right\}.
$$
:::

::: {.bloc .rem}
<span class="bloc-titre">Remarque : </span><br>
$f(I)$ est l'ensemble de toutes les images $f(x)$ lorsque $x$ parcourt $I$.
:::

::: {.bloc .ex}
<span class="bloc-titre">Exemple : </span><br>
Soit $f$ définie sur $I=[-3 \, ; \, 4]$ par $f(x)=x^2+2$.<br>
Alors, pour tout $x \in [-3\, ; \, 4]$, on montre que $f(x) \in [2\, ; \, 18]$.<br>
Ainsi $f(I)= [2\, ; \, 18]$.

:::


::: {.bloc .def}
<span class="bloc-titre">Définition : </span><br>
Soit $f$ définie sur $I$ et $g$ définie sur $J$ telles que $f(I)\subset J$.<br>
On appelle \emph{fonction composée} de $f$ par $g$ la fonction notée $h$ définie pour tout $x \in I$ par

$$
h(x)=(g \circ f)(x)=g(f(x)).
$$ 
:::

::: {.bloc .ex}
<span class="bloc-titre">Exemple : </span><br>
On considère les fonctions :
- $g$ définie sur $\R^*$ par $g(x) = \dfrac{1}{x}$ ;
- $f$ définie sur $\R$ par $f(x)=3x^2+1$ et à valeurs dans $[1~;~+\infty[\subset \R^*$.<br>
Ainsi $g \circ f$ est bien définie sur $\R$, et pour tout $x \in \R$,

$$h(x) = \frac{1}{3x^2+1}$$

:::

::: {.bloc .thm}
<span class="bloc-titre">Théorème (admis) : </span><br>
Soit $f$ une fonction définie et dérivable sur $I$ et à valeurs dans $J$, et $g$ une fonction définie et dérivable sur $J$.<br>
Alors la fonction $h$ définie par $$h(x)=g(f(x))$$
est dérivable sur $I$, et pour tout réel $x \in I$, 

$$
h'(x)= f'(x)\times g'\big(f(x)\big).
$$
:::

::: {.bloc .rem}
<span class="bloc-titre">Remarque : </span><br>
Dans le cadre du programme de première, on se borne aux fonctions $f$ affines, c'est-à-dire les fonctions

$$
f:x \longmapsto ax+b,
$$

où $a$ et $b$ sont des réels (respectivement le coefficient dominant et le terme constant de la fonction affine $f$).<br>
Ainsi, pour une fonction $g$ dérivable, en posant $h=g(ax+b)$, on a 
$$
h'(x) =a\, g'(ax+b).
$$
:::

::: {.bloc .ex}
<span class="bloc-titre">Exemple : </span><br>
Déterminer la dérivée de la fonction définie sur $I=]-2{,}5 \, ;\, +\infty[$ par $f(x) =\sqrt{2x+5}$.<br>
<details class="bloc cor"><summary>Afficher la correction</summary>
Soit $u$ définie sur $I$ par $u:x \longmapsto 2x+5$, et à valeurs dans $\R_+$.<br>
$u$ est dérivable sur $I$ et, pour tout $x \in I$, $u'(x)= 2$.<br>
Soit $v$ la fonction définie sur $\R_+^*$ par $v:x \longmapsto \sqrt{x}$.<br>
$v$ est dérivable sur $\R_+^*$ et, pour tout $x \in \R_+^*$, $v'(x)= \dfrac{1}{2\sqrt{x}}$.<br>
Ainsi $h=v \circ u$ est dérivable sur $I$. Or $$h'=(v'\circ u)\times u'.$$<br>
Pour tout réel $x \in I$,
$$
h'(x)= 2 \times \frac{1}{2\sqrt{2x+5}} = \frac{1}{\sqrt{2x+5}}.
$$
</details>
:::

::: {.bloc .ex}
<span class="bloc-titre">Exemple : </span><br>
Soit $f:x \longmapsto 1+x$ et $g:x \longmapsto x^n$.<br>
Alors la fonction $h$ définie sur $\R$ par $$h(x)=(g \circ f)(x)=(1+x)^n$$ est dérivable sur $\R$.<br>
On a $f'(x)=1$ et $g'(x)=n x^{\,n-1}$.<br>
Pour tout réel $x$, on a 

$$h'(x) = (g'\circ f)(x)\cdot f'(x)= n(1+x)^{n-1}.$$

:::

::: {.bloc .rem}
**Application à l'économie**<br>
On considère $t$ le taux d'intérêt composé annuel d'un certain placement. On décide de placer une somme $S$ sur une période de $n$ années. Au bout de $n$ années, on dispose alors de $(1+t)^n S$.<br>
Peut-on trouver un calcul simple lorsque $t$ est petit ?<br>
On rappelle que l'approximation affine de $f$ en $a$ est donnée par $$f(a+h) \approx f(a)+h\,f'(a).$$<br>
On considère l'approximation affine de $(1+t)^n$. <br>
Pour de petites valeurs de $t$, on a $$(1+t)^n \approx 1^n + t \times \big(n \, 1^{\,n-1}\big)=1+n\,t.$$<br>
On déduit qu'après $n$ années, le montant disponible est alors environ $S(1+nt)$, où $t$ est le taux d'évolution.
:::



<div class="nav-pages">
  <a class="prev" href="operation.html">⬅️</a>
  <a class="next" href="applications.html">➡️</a>
</div>