---
title: "Fonction dérivée - Dérivées usuelles"
description: "Fonctions dérivées, dérivées des fonctions usuelles"
format:
  html:
    toc: true
    number-sections: false
order: 3
---

::: {.bloc .def}
<span class="bloc-titre">Définition :</span>  
On dit que $f$ est dérivable sur $I$ lorsque $f$ est dérivable en tout point $a$ de $I$.

On appelle alors \textbf{fonction dérivée} de la fonction $f$, la fonction notée $f'$, définie sur $I$ par 
$$f' : x \longmapsto f'(x)$$
:::

::: {.bloc .exo}
<span class="bloc-titre">Exemple :</span>  
On considère la fonction $f$, définie par $f(x)=2x^2-3x+5$. Déterminons la fonction dérivée associée.

<details class="bloc cor"><summary>Afficher la correction</summary>
Pour tout $h$ non nul et tout réel $a$, 
$$
\tau_a(h) = \dfrac{f(a+h) - f(a)}{h} = \dfrac{2(a+h)^2 - 3(a+h) + 5 - (2a^2 - 3a + 5)}{h}
$$

On développe :
$$
\tau_a(h)= \dfrac{2(a^2 + 2ah + h^2) - 3a - 3h + 5 - 2a^2 + 3a - 5}{h}
= \dfrac{4ah + 2h^2 - 3h}{h} = 4a + 2h - 3
$$

Or 
$$
\lim_{h \to 0} \tau_a(h) = \lim_{h \to 0} 4a + 2h - 3 = 4a - 3
$$

La limite existe, donc $f$ est dérivable en $a$, et $f'(a) = 4a-3$.

On déduit alors que la fonction dérivée de la fonction $f$ est la fonction $f'$ définie sur $\R$ par $f'(x)=4x-3$.
</details>
:::

::: {.bloc .thm}
<span class="bloc-titre">Théorème :</span>  
On considère une fonction $f$ définie sur son ensemble de définition $D_f$.

| Fonction $f$             | Ensemble de définition                  | Fonction dérivée $f'$             | Ensemble de dérivabilité                  |
|--------------------------|------------------------------------------|-----------------------------------|-------------------------------------------|
| $k$                      | $\mathbb{R}$                             | $0$                               | $\mathbb{R}$                              |
| $ax$                     | $\mathbb{R}$                             | $a$                               | $\mathbb{R}$                              |
| $x^2$                    | $\mathbb{R}$                             | $2x$                              | $\mathbb{R}$                              |
| $\sqrt{x}$               | $\mathbb{R}_+$                           | $\dfrac{1}{2\sqrt{x}}$            | $\mathbb{R}_+^*$                          |
| $\dfrac{1}{x}$           | $]-\infty\,; 0[ \cup ]0\,; +\infty[$     | $-\dfrac{1}{x^2}$                 | $]-\infty\,; 0[ \cup ]0\,; +\infty[$      |
| $ax^2 + bx + c$          | $\mathbb{R}$                             | $2ax + b$                         | $\mathbb{R}$                              |
:::

<details class="bloc demo"><summary>Démonstration :</summary>
On démontre quelques cas :

- admis pour les deux premiers cas (facile à vérifier).  
- Soit $f$ définie sur $\R$ par $f(x) = x^2$.  
Pour tout $a,h \in \R$,  
$$(a+h)^2 - a^2 = 2ah+h^2$$  
Donc  
$$\dfrac{f(a+h) - f(a)}{h} = 2a+h$$  
Donc en faisant tendre $h$ vers $0$, on obtient  
$f'(a)= 2a$.  

- Soit $f$ définie sur $\R_+$ par $f(x) = \sqrt{x}$.  
Pour tout $a \in \R_+$ et $h \in \R^*$ tel que $a+h > 0$,  
$$\sqrt{a+h} - \sqrt{a} = \dfrac{a + h - a}{\sqrt{a+h} + \sqrt{a}} = \dfrac{h}{\sqrt{a+h} + \sqrt{a}}$$  
Ainsi
$$\dfrac{f(a+h) - f(a)}{h} = \dfrac{1}{\sqrt{a+h} + \sqrt{a}}$$  
Donc en faisant tendre $h$ vers $0$, on obtient $f'(a)= \dfrac{1}{2 \sqrt{a}}$.  
</details>

::: {.bloc .rem}
<span class="bloc-titre">Remarque :</span>  
Soit $n \in \N^*$, on définie les fonctions $f$ et $g$ par 


- $f:x \longmapsto x^n$ définie sur $\R$,  
- $g:x \longmapsto \dfrac{1}{x^n}$ définie sur $]-\infty\,;\,0[ \cup ]0\,;\,+\infty[$,  

on démontre par récurrence (programme de terminale) que
$$
f':x \longmapsto n x^{n-1} 
\quad \et \quad 
g':x \longmapsto -\dfrac{n}{x^{n+1}}.
$$

Par exemple si $f:x \longmapsto x^3$ et $g:x \longmapsto \dfrac{1}{x^5}$, alors 
$$
f'(x)=3x^2 \qquad \et \qquad g'(x)=-\dfrac{5}{x^6}.
$$
:::



::: {.bloc .exo}
<span class="bloc-titre">Exemple :</span>  
On considère la fonction $f$ définie sur $\R$ par $f'(x)= 3x^2-5x+3$.

1. Déterminer l'équation réduite de la tangente à l représetnation graphique de $f$ au point d'abscisse $2$.


  <details class="bloc cor"><summary>Afficher la correction</summary>
  $f$ est une fonction polynôme donc dérivable sur son ensembnle de définition $\R$.
  
  Pour tout $x \in \R$, 
  $$f'(x)=2 \times 3x -5 = 6x-5$$

  Or $$M(x \, ;\,y) \in T_2 \Longleftrightarrow T_2 \,: \, y= f'(2)(x-2) + f(2) \Longleftrightarrow T_2 \,: \, y= 7(x-2) + 5  \Longleftrightarrow T_2 \,: \, y=7x-9$$

  Ainsi 

  $$T_2 \,:\, y=7x-9
    $$

  </details>

2. Déterminer la position relative de la représentation graphique de $f$ par rapport à sa tangente.
  
  <details class="bloc cor"><summary>Afficher la correction</summary>
 Pour tout réel $x$, 
$$f(x)-(7x-9) -5x+3 = 3x^2-5x+3 - 7x + 9 = 3x^2 -12x +12 =3 (x^2-4x+4)= 3(x-2)^2$$

On déduit donc que pour tout réel $x$, $$f(x) \geqslant 7x-9$$

Donc que la représentation graphique de $f$ est située au-dessus de $T_2$


  </details>


:::


::: {.bloc .exo}
<span class="bloc-titre">Exemple :</span>  
On considère la fonction $f$ définie sur $\R_+$ par $f(x) = \sqrt{x}$.

1. Déterminer l'approximation affine de $f(1+x)$ pour $x$ proche de $0$.

  <details class="bloc cor"><summary>Afficher la correction</summary>
  On sait que $f$ est dérivable en $1$ et que $f'(1) = \dfrac{1}{2\sqrt{1}} = \dfrac{1}{2}$.

  De plus $f(1) = \sqrt{1} = 1$.
  Ainsi, D'après la formule de l’approximation affine,
  $ f(1+x) \approx f(1) + x f'(1) $$
  On obtient l'approximation classique suivante, valable pour $x$ proche de $0$ :
$$ \sqrt{1+x} \approx 1 + \dfrac{1}{2}x $$

  </details>

2. Calculer une valeur approchée de $\sqrt{1,08}$ et comparer avec la calculatrice.  

  <details class="bloc cor"><summary>Afficher la correction</summary>
  Par l'approximation affine ($x=0,08$) :
    $$ \sqrt{1+0,08} \approx 1 + \dfrac{0,08}{2} \approx 1,04 $$
  </details>
:::

::: {.bloc .rem}
<span class="bloc-titre">Remarque : </span><br>
  A l'aide de la calculatrice on trouve, 
    $$ \sqrt{1,08} \approx 1,03923... $$
L'erreur commise est inférieure à $0,001$.

:::
<div class="nav-pages">
  <a class="prev" href="tangente.html">⬅️</a>
</div>