---
title: "Dérivation et concavité"
format:
  html:
    toc: true
    number-sections: false
description: "Dérivée, taux d'accroissement, étude d ela convexité"
order: 6
---


::: {.bloc .def}
<span class="bloc-titre">Définition : </span>

Soit $\mathscr{P}$ un plan et $A$ un point de l'espace.
Il existe une unique droite passant par $A$ et orthogonale à $\mathscr{P}$. Le point d'intersection entre cette droite et $\mathscr{P}$ est appelé projeté orthogonal de $A$ sur $\mathscr{P}$.

:::



::: {.bloc .rem}
<span class="bloc-titre">Remarque : </span>

Démontrer que la distance du point $A$ au plan $\mathscr{P}$ est la plus petite des longueurs $AM$ où $M \in \mathscr{P}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

En effet soit $M$ un point quelconque de $\mathscr{P}$, alors $AMH$ est rectangle en $H$, donc $AM^2=AH^2+MH^2$, ainsi $AM > AH$.

</details>

:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple :<span class="exemp-extra">   </span></div>

On considère le point $A(1;-2;1)$ et le plan $\mathscr{P}$ d'équation cartésienne $2x-5y+3z+4=0$.
Déterminer les coordonnées du projeté orthogonal $H$ de $A$ sur $\mathscr{P}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

Soit $\ve{n}(2;-5;3)$ un vecteur normal de $\mathscr{P}$.
$H$ étant le projeté orthogonal de $A$ sur $\mathscr{P}$, alors $\ve{AH}$ et $\ve{n}$ sont colinéaires.
Donc il existe un réel $t \in \mathbb{R}$ tel que $\ve{AH} = t \ve{n}$.
On en déduit de cette égalité que :
$$(1) \qquad \left\{\begin{array}{l}
x_H=1+2t\\
y_H=-2-5t\\
z_H=1+3t
\end{array}\right.$$
De plus $H \in \mathscr{P}$, donc ses coordonnées vérifient l'équation du plan. Ainsi :
$$2(1+2t)-5(-2-5t)+3(1+3t)+4=0.$$
D'où $38t=-19$ donc $t=-\dfrac{1}{2}$.
On trouve les coordonnées de $H$ en remplaçant $t$ par sa valeur dans (1).

</details>

:::

::: {.bloc .thm}
<span class="bloc-titre">Propriété (hors programme) : </span>

Soit $A (x_A ; y_A ; z_A)$ et $\mathscr{P}$ un plan d'équation cartésienne $ax+by+cz+d=0$.
On note $H$ le projeté orthogonal de $A$ sur $\mathscr{P}$, alors :
$$d(A, \mathscr{P}) = \dfrac{|a x_A +b y_A +c z_A +d|}{\sqrt{a^2+b^2+c^2}}$$

:::

<details class="bloc demo"><summary>Démonstration : </summary>

Le vecteur $\ve{AH}$ est un vecteur normal au plan $\mathscr{P}$, donc il existe un réel $t$ tel que $\ve{AH} = t \ve{n}$ où $\ve{n} \begin{pmatrix} a\\b\\c \end{pmatrix}$ est un vecteur normal de $\mathscr{P}$.
On en déduit que $x_H=x_A+at$, $y_H=y_A+bt$ et $z_H=z_A+ct$.
$H$ appartenant à $\mathscr{P}$, ses coordonnées vérifient l'équation du plan, donc (après calcul) :
$$(a^2+b^2+c^2)t=-(ax_A+by_A+c z_A+d)$$
donc
$$t=-\dfrac{ax_A+by_A+c z_A+d}{a^2+b^2+c^2}.$$
De plus $AH^2=t^2(a^2+b^2+c^2)$.
D'où :
$$AH=\dfrac{|a x_A +b y_A +c z_A +d|}{\sqrt{a^2+b^2+c^2}}.$$

</details>



::: {.bloc .ex}
<div class="bloc-titre">Exemple :<span class="exemp-extra"> (Extrait Bac Métropole 2017) </span></div>

L'espace est muni d'un repère $(O \, ; \, \ve{i}, \ve{j}, \ve{k})$.
Soit $\mathcal{P}$ le plan d'équation cartésienne : $2x - z - 3 = 0$ et $A$ le point de coordonnées $(1~;~a~;~a^2)$ où $a$ est un nombre réel.

1. Justifier que, quelle que soit la valeur de $a$, le point $A$ n'appartient pas au plan $\mathcal{P}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

$2x_A-z_A-3=2-a^2-3=-1-a^2 < 0$, donc $2x_A-z_A-3 \neq 0$.
Cela signifie que $A$ n'appartient pas au plan $\mathcal{P}$.

</details>

2. 
    a. Déterminer une représentation paramétrique de la droite $\mathcal{D}$ (de paramètre $t$) passant par le point $A$ et orthogonale au plan $\mathcal{P}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

$\ve{n}\begin{pmatrix} 2\\0\\-1 \end{pmatrix}$ est normal à $\mathcal{P}$ donc directeur de $\mathcal{D}$, et $A(1~;~a~;~a^2) \in \mathcal{D}$.
Donc $\mathcal{D} : \begin{cases} x=1+2t \\ y=a \\ z=a^2-t \end{cases}, \, t \in \mathbb{R}$.

</details>

    b. Soit $M$ un point appartenant à la droite $\mathcal{D}$, associé à la valeur $t$ du paramètre dans la représentation paramétrique précédente. Exprimer la distance $AM$ en fonction du réel $t$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

Dans un repère orthonormé :
$AM^2=(x_M-x_A)^2 +(y_M- y_A)^2 +(z_M-z_A)^2$
$=(1 + 2t - 1)^2 +(a - a)^2 +(a^2-t-a^2)^2 = (2t)^2 + (-t)^2 = 5t^2$.
Donc $AM=|t|\sqrt{5}$.

</details>

3. On note $H$ le point d'intersection du plan $\mathcal{P}$ et de la droite $\mathcal{D}$ orthogonale à $\mathcal{P}$ et passant par le point $A$. Le point $H$ est appelé projeté orthogonal du point $A$ sur le plan $\mathcal{P}$ et la distance $AH$ est appelée distance du point $A$ au plan $\mathcal{P}$.
Existe-t-il une valeur de $a$ pour laquelle la distance $AH$ du point $A$ de coordonnées $(1~;~a~;~a^2)$ au plan $\mathcal{P}$ est minimale ? Justifier la réponse.

<details class="bloc cor"><summary>Afficher la correction :</summary>

$H$ est l'intersection de $\mathcal{D}$ et $\mathcal{P}$, ses coordonnées vérifient donc :
$2(1+2t) - (a^2-t) - 3 = 0 \Longleftrightarrow 2 + 4t - a^2 + t - 3 = 0 \Longleftrightarrow 5t = a^2+1$.
On en déduit $t = \dfrac{a^2+1}{5}$.
D'après la question précédente, $AH = \dfrac{a^2+1}{5}\sqrt{5} = \dfrac{a^2+1}{\sqrt{5}}$.
Cette distance est minimale lorsque $a^2$ est minimal, c'est-à-dire pour $a=0$.
La distance minimale est alors $AH = \dfrac{1}{\sqrt{5}} = \dfrac{\sqrt{5}}{5}$.
</details>

:::


::: {.bloc .ex}
<div class="bloc-titre">Exemple :<span class="exemp-extra"> (Extrait Bac Métropole 2017) </span></div>

L'espace est muni d'un repère $(O \, ; \, \ve{i}, \ve{j}, \ve{k})$.
Soit $\mathcal{P}$ le plan d'équation cartésienne : $2x - z - 3 = 0$ et $A$ le point de coordonnées $(1~;~a~;~a^2)$ où $a$ est un nombre réel.

1. Justifier que, quelle que soit la valeur de $a$, le point $A$ n'appartient pas au plan $\mathcal{P}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

$2x_A-z_A-3=2-a^2-3=-1-a^2 < 0$, donc $2x_A-z_A-3 \neq 0$.
Cela signifie que $A$ n'appartient pas au plan $\mathcal{P}$.

</details>

2. 
    a. Déterminer une représentation paramétrique de la droite $\mathcal{D}$ (de paramètre $t$) passant par le point $A$ et orthogonale au plan $\mathcal{P}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

$\ve{n}\begin{pmatrix} 2\\0\\-1 \end{pmatrix}$ est normal à $\mathcal{P}$ donc directeur de $\mathcal{D}$, et $A(1~;~a~;~a^2) \in \mathcal{D}$.
Donc $\mathcal{D} : \begin{cases} x=1+2t \\ y=a \\ z=a^2-t \end{cases}, \, t \in \mathbb{R}$.

</details>

    b. Soit $M$ un point appartenant à la droite $\mathcal{D}$, associé à la valeur $t$ du paramètre dans la représentation paramétrique précédente. Exprimer la distance $AM$ en fonction du réel $t$.

<details class="bloc cor"><summary>Afficher la correction :</summary>

Dans un repère orthonormé :
$AM^2=(x_M-x_A)^2 +(y_M- y_A)^2 +(z_M-z_A)^2$
$=(1 + 2t - 1)^2 +(a - a)^2 +(a^2-t-a^2)^2 = (2t)^2 + (-t)^2 = 5t^2$.
Donc $AM=|t|\sqrt{5}$.

</details>

3. On note $H$ le point d'intersection du plan $\mathcal{P}$ et de la droite $\mathcal{D}$ orthogonale à $\mathcal{P}$ et passant par le point $A$. Le point $H$ est appelé projeté orthogonal du point $A$ sur le plan $\mathcal{P}$ et la distance $AH$ est appelée distance du point $A$ au plan $\mathcal{P}$.
Existe-t-il une valeur de $a$ pour laquelle la distance $AH$ du point $A$ de coordonnées $(1~;~a~;~a^2)$ au plan $\mathcal{P}$ est minimale ? Justifier la réponse.

<details class="bloc cor"><summary>Afficher la correction :</summary>

$H \in \mathcal{D}$ donc $AH = |t|\sqrt{5}$ avec $t$ le paramètre associé à $H$.
De plus $H \in \mathcal{P}$, donc ses coordonnées vérifient $2x_H-z_H-3=0$.
Ainsi : $2(1+2t) -(a^2-t)-3=0 \Longleftrightarrow t=\dfrac{a^2+1}{5}$.
La distance $AH$ vaut alors $AH=\dfrac{a^2+1}{\sqrt{5}}$.
Elle est minimale quand $a^2$ est minimal, donc quand $a=0$.
Finalement $A(1~;~0~;~0)$ est le point pour lequel la distance $AH$ est minimale.

</details>

:::


:::















<div class="nav-pages">
 <a class="prev" href="propriete.html">⬅️</a>
  <a class="next" href="composition.html">➡️</a>
</div>
