---
title: "Notion d'épreuves indépendantes"
format:
  html:
    toc: true
    number-sections: false
description: "Bernoulli - Binomiale"
order: 2
---


## Indépendance de deux expériences aléatoires

::: {.bloc .def}
<span class="bloc-titre">Définition : </span>

Soient $I$ et $J$ deux sous-ensembles de $\N$. On considère deux expériences aléatoires $\mathscr{E}_1$ et $\mathscr{E}_2$ dont les univers associés sont respectivement $\Omega_1$ et $\Omega_2$.

On dit qu'une expérience aléatoire est la succession de deux expériences indépendantes $\mathscr{E}_1$ et $\mathscr{E}_2$ lorsque :

* L'univers associé $\Omega$ est le produit cartésien des univers $\Omega_1$ et $\Omega_2$
* Pour tout $\omega \in \Omega$ il existe $(i,j) \in I\times J$ tel que $\omega=(x_i, y_j) \in \Omega_1 \times \Omega_2$ et $P(\omega)= P(x_i) \times P(y_j)$
:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple :<span class="exemp-extra">   </span></div>

Un appareil ménager peut présenter après sa fabrication deux types de défauts : un défaut d’apparence (A) et un défaut de fonctionnement (F).

La probabilité que l’appareil présente un défaut d’apparence vaut $0,02$ et la probabilité que l’appareil présente au moins l’un des deux défauts vaut $0,069$. On suppose que les deux types de défauts sont indépendants. 

1. Déterminer l'ensemble $\Omega$.
2. On choisit un des appareils. Quelle est la probabilité que l’appareil présente le défaut F ?

<details class="bloc cor"><summary>Afficher la correction :</summary>

1. $\Omega_1 = \{A, \bar{A} \}$ et $\Omega_2=\{F,\bar{F}\}$.
   Ainsi $\Omega= \Omega_1 \times \Omega_2=\{(A,F) \, ; \, (\bar{A},F) \, ; \, (\bar{A},\bar{F}) \, ; \, (A,\bar{F})\}$

2. On sait que (théorème fondamental) :
   $$P(A \cap F) + P(A \cup F) = P(A) + P(F)$$
   Donc :
   $$P(F) = P(A \cap F) + P(A \cup F) - P(A)$$
   De l'indépendance des expériences aléatoires on déduit que :
   $$P(F) = P(A) \times P(F) + P(A \cup F) - P(A)$$
   Donc :
   $$P(F) = \dfrac{P(A \cup F) - P(A)}{1-P(A)} = \dfrac{0,069-0,02}{1-0,02} = \dfrac{0,049}{0,98} = 0,05$$
</details>
:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple :<span class="exemp-extra">   </span></div>

On lance successivement un dé tétraédrique numéroté de 1 à 4 et un dé normal à 6 faces. On note $P_1$ la loi de probabilité associée au lancer du 1er dé, et $P_2$ la loi de probabilité associée au lancer du second dé.

Le résultat du premier dé n’a pas d’influence sur le résultat du deuxième dé donc les expériences sont indépendantes.

L’univers est donc : $\Omega = \{1, 2, 3, 4\} \times \{1, 2, 3, 4, 5, 6 \}$
Cet univers est constitué de $24$ issues.

* Le couple $(3, 5)$ est une issue possible ;
* Le couple $(5, 3)$ est une issue qui est impossible.

De plus $P((3,5)) = P_1(\{3\}) \times P_2(\{5\}) = \dfrac{1}{4} \times \dfrac{1}{6} = \dfrac{1}{24}$
:::

::: {.bloc .thm}
<span class="bloc-titre">Propriété (admise) : </span>

Soit une succession de $n$ expériences indépendantes dont les univers associés sont respectivement $\Omega_1, \Omega_2, \dots \Omega_n$.

L’univers associé $\Omega$ à cette succession de $n$ épreuves est le produit cartésien :
$$\Omega = \Omega_1 \times \Omega_2 \times \dots \times \Omega_n$$

De plus en notant les lois de probabilité respectives  $P_1, P_2, \dots, P_n$ et en considérant $x=(x_1, x_2, \dots, x_n)$ une issue possible :
$$P(x)= P_1(x_1) \times P_2(x_2) \times \dots \times P_n(x_n)$$
:::

::: {.bloc .rem}
<span class="bloc-titre">Remarque : </span><br>

- On représente généralement la situation à l'aide d'un arbre, où chacun des chemins corresponds aux différentes issues.
- Lorsque les épreuves sont indépendantes, la notion d'épreuves successives est artificielle. Par exemple, on peut lancer trois dés simultanément (il suffit alors de donner un numéro d'ordre à chacun des dés pour obtenir un triplet de résultat).$
:::


<div class="nav-pages">
 <a class="prev" href="historique.html">⬅️</a>
  <a class="next" href="bernoulli1.html">➡️</a>
</div>
