---
title: "Opération sur les fonctions continues"
format:
  html:
    toc: true
    number-sections: false
description: "Somme, produit et composée de fonctions continues"
order: 2
---


_____


::: {.bloc .thm}
<span class="bloc-titre">Propriété (admise) : </span>

On considère $f$ et $g$ deux fonctions continues en $x_0$ et $\lambda, \mu \in \mathbb{R}$, alors les fonctions $\lambda f$, $\lambda f+ \mu g$, $fg$ sont continues en $x_0$.  
Si de plus $g$ ne s'annule **pas** en $x_0$, alors $\dfrac{f}{g}$ est continue en $x_0$.
:::

On déduit de ce théorème (dont la preuve repose sur la définition **de la** continuité) que :

::: {.bloc .thm}
<span class="bloc-titre">Propriété : </span>

* Les fonctions polynômes sont continues sur $\mathbb{R}$ ;
* Les fonctions rationnelles sont continues sur leur ensemble de définition.
:::

::: {.bloc .thm}
<span class="bloc-titre">Propriété : </span>

Soit $f$ une fonction définie sur $I$ et continue en $x_0 \in I$. Soit $g$ une fonction définie sur $J$ **tel que** $f(I) \subset J$.  
Si $g$ est continue en $f(x_0)$ alors la fonction $g \circ f$ est continue en $x_0$.
:::



<details class="bloc demo"><summary>Démonstration : </summary>

Soit $\epsilon >0$. La continuité de $g$ en $f(x_0)$ donne :
$$\exists \eta_1 >0, \, \forall y \in J, \, (|y-f(x_0)| \leqslant \eta_1 \Rightarrow |g(y)-g(f(x_0)) | \leqslant \epsilon)$$
et puisque $f$ est continue en $x_0$, pour le $\eta_1$ précédent on a :
$$\exists \eta_2 >0, \, \forall x \in I, \ (|x-x_0| \leqslant \eta_2 \Rightarrow |f(x)-f(x_0)| \leqslant \eta_1)$$
Ainsi, 
$$\forall x \in I, \, (|x-x_0| \leqslant \eta_2 \Rightarrow |f(x)-f(x_0)| \leqslant \eta_1 \Rightarrow |g(f(x))-g(f(x_0)) | \leqslant \epsilon)$$
Par définition :
$$\lim_{x \to x_0} (g \circ f)(x)=(g \circ f)(x_0)$$
</details>

::: {.bloc .thm}
<span class="bloc-titre">Propriété : </span>

On déduit que : si $f$ est continue sur $I$ alors 
* $|f|$ est continue sur $I$ ;
* $\sqrt{f}$ est continue en tout point où $f$ est positive.
* $\e^{f}$ est continue sur $I$.
:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple :<span class="exemp-extra">   </span></div>

On a montré précédemment que la fonction $\exp$ est continue en tout réel $x$ et que la fonction racine carrée est continue en tout point de $\mathbb{R}_+$.  
On déduit du théorème de composition que la fonction $f:x \longmapsto \e^{\sqrt{x}}$ est continue en tout point de $\mathbb{R}_+$.
:::


<div class="nav-pages">
 <a class="prev" href="continuite.html">⬅️</a>
  <a class="next" href="tvi.html">➡️</a>
</div>
