---
title: "Lien coefficients - racines"
format:
  html:
    toc: true
    number-sections: false
description: "Faire le lien entre les coefficients et les solutions d'une équation - Système d'équation à 2 inconnues"
order: 3
---

### Liens entre racines et coefficients

::: {.bloc .thm}
<span class="bloc-titre">Théorème :</span>  

Soit $f(x) = ax^2 + bx + c$ une fonction polynôme du second degré, de racine $x_1$ et $x_2$ (éventuellement $x_1=x_2$). 

Alors en appelant $S$ la somme des racines et $P$ le produit des racines, on a 

$$S = x_1 + x_2 = - \frac{b}{a} \et P = x_1 \times x_2 = \frac{c}{a}$$


et pour tout réel $x$,  

$$f(x) = a \left(x^2 - S x + P \right)$$
:::

<details class="bloc demo"><summary>Démonstration :</summary>

Soit $f(x) = ax^2 + bx + c$ une fonction polynôme du second degré, de racine $x_1$ et $x_2$, alors 
$$S = x_1 + x_2 = \frac{-b + \sqrt{\Delta}}{2a}+  \frac{-b + \sqrt{\Delta}}{2a}= -\frac{b}{a}$$

et 

$$P = x_1 x_2 = \frac{-b + \sqrt{\Delta}}{2a} \times  \frac{-b - \sqrt{\Delta}}{2a}
=\frac{(-b)^2 - \Delta}{4a^2} = \frac{b^2 - b^2 + 4ac}{4a^2} =\frac{c}{a}
$$

Réciproquement, supposons $ax^2 - aSx + aP = 0$.

Cette équation admet pour discriminant 

$$\Delta = (-aS)^2 - 4aP = a((x_1 + x_2)^2 - 4x_1 x_2) = a(x_1^2 + x_2^2 + 2x_1x_2 - 4x_1 x_2) =a (x_1-x_2)^2$$

Ainsi les solutions $u$ et $v$ de cette équation sont 

$$u = \frac{S + x_1 - x_2}{2} \et v = \frac{S -( x_1 -x_2)}{2}$$
Donc 

$$u = x_1 \quad \text{ et } \quad  v = x_2$$

</details>

::: {.bloc .rem}
<span class="bloc-titre">Remarque :</span>  
Lorsque l’on connaît l’expression algébrique d’un polynôme du second degré, et une de ses racines, alors on connaît automatiquement la seconde racine.  

On peut chercher, par exemple, parmi les valeurs $-2$, $-1$, $1$ ou $2$ (éventuellement $\sqrt{2}$), si une de ces valeurs n’est pas une racine du polynôme. Si c’est le cas, on peut alors la caractériser de racine évidente.
:::

::: {.bloc .ex}
<span class="bloc-titre">Exemple :</span>  

Soit $f(x) = -5x^2 + 3x + 14$.  
$x_1 = 2$ est une racine évidente, en effet :  

$$-5 \times 2^2 + 3 \times 2 + 14 = 0$$  

Le polynôme admettant une racine, il en admet une deuxième $x_2$, et :  

$$x_1 x_2 = \frac{14}{-5} \quad \Rightarrow \quad x_2 = \frac{14}{2 \times -5} = -\tfrac{7}{5}$$
:::







<div class="nav-pages">
  <a class="prev" href="coefficient.html">⬅️</a>
</div>


<div class="nav-pages">
  <a class="prev" href="signe.html">⬅️</a>
  <a class="next" href="parabole.html">➡️</a>
</div>