---
title: "Produit scalaire et orthogonalite"
format:
  html:
    toc: true
    number-sections: false
description: "Pour montrer que des droites sont perpendiculaires"
order: 2
---

___

::: {.bloc .def}
<span class="bloc-titre">Définition : </span><br>

On dit que deux vecteurs non nuls sont orthogonaux lorsque les droites support sont perpendiculaires.
:::

::: {.bloc .thm}
<span class="bloc-titre">Propriété : Produit scalaire et orthogonalité</span><br>

Soient $\ve{u}$ et $\ve{v}$ deux vecteurs non nuls, alors
$$\ve{u}.\ve{v} = 0 ~~\Longleftrightarrow~~ \ve{u}~\perp \ve{v}$$
:::

<details class="bloc demo"><summary>Démonstration : </summary>

Soit $\ve{u} \neq \ve{0}$ et $\ve{v} \neq \ve{0}$.  
$\ve{u}.\ve{v} = 0 \Longleftrightarrow \|\ve{u}\|\times \|\ve{v}\| \cos(\theta)  = 0 \Longleftrightarrow \cos(\theta)=0 \Longleftrightarrow \theta= \pm 90^\circ$.
</details>

::: {.bloc .ex}
<div class="bloc-titre">Exemple <span class="exemp-extra"></span></div>

On considère un triangle tel que $AB=5$, $BC =13$ et $AC=12$.  
Déterminer $\ve{AC}.\ve{AB}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>
On a $$BC^2=13^2 = 169 = 25+ 144 = AB^2 + AC^2$$

On déduit que $ABC$ est un triangle rectangle en $A$, donc que $(AB) \perp (AC)$.  

Donc $\ve{AB}.\ve{AC} = 0$.
</details>
:::

::: {.bloc .thm}
<span class="bloc-titre">Propriété : Définition par le projeté orthogonal</span><br>

Soient $\ve{u}$ et $\ve{v}$ deux vecteurs non nuls du plan tels que $\ve{u}=\ve{AB}$ et $\ve{v} = \ve{AC}$.  

On note $H$ le projeté orthogonal de $C$ sur la droite $(AB)$.

$$\ve{u}.\ve{v} = \ve{AB}.\ve{AC} = \left\{\begin{array}{l}
AB \times AH~~~~\text{si}~~~\ve{AB} \text{ et } \ve{AH}~~\text{sont de même sens}.\\
-AB \times AH~~~~\text{si}~~~\ve{AB} \text{ et } \ve{AH}~~\text{sont  de sens contraire.}
\end{array} \right.$$
:::

On note $\ve{w}$ la projection orthogonale de $\ve{v}$ sur la droite $(AB)$, de sorte que $\ve{w}=\ve{AH}$.



<details class="bloc demo"><summary>Démonstration : </summary>

On procède par disjonction des cas :

1. On suppose que $H \neq A$, on a donc $ABH$ rectangle en $H$ et, par la trigonométrie dans un triangle rectangle, on a $AH= AC \cos(\widehat{HAC})$.
    a. On suppose que $H \in [AB)$. Ainsi $\widehat{HAC} = \widehat{BAC}$.  

        Donc 
        $$\ve{AB}.\ve{AC} = AB \times AC \times \cos(\widehat{BAC}) = AB \times AC \times \cos(\widehat{CAH}) = AB \times AH = \ve{AB}.\ve{AH}$$

    b. On suppose que $H \notin [AB)$, alors $\widehat{HAC} = 180^\circ- \widehat{BAC}$.  
        
        Donc 
        $$\ve{AB}.\ve{AC} = AB \times AC \times \cos(\widehat{BAC}) = AB \times AC \times \cos(180^\circ-\widehat{CAH}) = -AB \times AC \times \cos(\widehat{HAC}) = \ve{AB}.\ve{AH}$$
2. Si $H$ est en $A$, alors $\widehat{BAC}$ est un angle droit, donc le produit scalaire $\ve{AB}.\ve{AC} = 0 = \ve{AB}.\ve{AH}$
</details>

::: {.bloc .ex}
<div class="bloc-titre">Exemple <span class="exemp-extra"></span></div>

On considère $ABC$ un triangle rectangle en $A$ tel que $AB=5$ et $AC=7$.  

Déterminer $\ve{CA}.\ve{CB}$.

<details class="bloc cor"><summary>Afficher la correction :</summary>
$ABC$ rectangle en $A$, donc $A$ est le projeté orthogonal de $B$ sur $(AC)$. 

On déduit alors que $$\ve{CA}.\ve{CB} = CA \times CA = 49$$
</details>
:::

::: {.bloc .rem}
<span class="bloc-titre">Remarque : Relation fondamentale</span><br>

Si $A$, $B$, $C$ et $D$ sont 4 points du plan, avec $A$ et $B$ distincts. 
 
On note $C'$ le projeté orthogonal de $C$ sur $(AB)$ et $D'$ celui de $D$ sur $(AB)$ alors $$\ve{AB}.\ve{CD} = \ve{AB}.\ve{C'D'}$$
:::

::: {.bloc .ex}
<div class="bloc-titre">Exemple <span class="exemp-extra"></span></div>

Soit $ABC$ un triangle tel que $AB = AC = 4$ et $\widehat{ABC} = \dfrac{\pi}{6}$.  
Déterminons la mesure de $BC$.

<details class="bloc cor"><summary>Afficher la correction :</summary>
On a 
$$\ve{BA}.\ve{BC} = BA \times BC \times \cos \left(\widehat{ABC} \right) = 4 \times BC \times \dfrac{\sqrt{3}}{2}$$

De plus, dans un triangle isocèle, la médiane et la médiatrice issues du sommet principal sont confondues.  

Soit $H$ le milieu de $[BC]$, alors $(AH) \perp (BC)$.  

$H$ est donc le projeté orthogonal de $A$ sur $[BC]$ et $\ve{BH} =\dfrac12 \ve{BC}$.  

Ainsi 

$$\ve{BC}.\ve{BA} = \ve{BC}.\ve{BH} = \dfrac{1}{2} \ve{BC}^2$$

On déduit donc que 

$$4 \times BC \times \dfrac{\sqrt{3}}{2}= \dfrac{1}{2} BC^2$$

D'où $BC= 4 \sqrt{3}$
</details>
:::


<div class="nav-pages">
  <a class="prev" href="definition.html">⬅️</a>
  <a class="next" href="Proprietes.html">➡️</a>
</div>