---
title: "Les quantificateurs"
format:
  html:
    toc: true
    number-sections: false
description: "Implication - Quantificateurs"
order: 3
---

### Implication, réciproque, équivalence

::: {.bloc .def}

<span class="bloc-titre">Définition : </span><br>
Soient $P$ et $Q$ deux propositions.

1. On dit que $P$ implique $Q$, et on note $(P \Longrightarrow Q)$, lorsque : si $P$ est vraie alors $Q$ est vraie.  
2. On appelle réciproque de $(P \Longrightarrow Q)$ la proposition $(Q \Longrightarrow P)$.  
3. On dit que $P$ est équivalente à $Q$ lorsque $(P \Longrightarrow Q)$ et $(Q \Longrightarrow P)$. On note alors $(P \Longleftrightarrow Q)$.
:::

::: {.bloc .rem}

<span class="bloc-titre">Remarque : </span><br>

- $\Longrightarrow$ n'est pas l'abréviation du mot « donc ». La déduction d'information à l'aide d'une implication repose sur la véracité de deux énoncés et l'utilisation d'une règle de logique.  
- De façon, peut-être, surprenante, l'énoncé $P \Longrightarrow Q$ est toujours vrai si $P$ est faux.  
  En effet, la véracité de $(P \Longrightarrow Q)$ ne suffit pas à elle seule à conclure quoi que ce soit sur $Q$.  
  $(2>3 \Longrightarrow 4>6)$ est une proposition mathématique vraie, mais $4 \not> 6$.  
  L'idée sous-jacente est de dire que l'on peut toujours dire ce que l'on veut en partant de quelque chose de faux.
:::

**Table de vérité et implication**

| $P$ | $Q$ | $P \Longrightarrow Q$ |
|:---:|:---:|:---------------------:|
| F   | F   | V |
| F   | V   | V |
| V   | F   | F |
| V   | V   | V |

| $P$ | $Q$ | non $P$ ou $Q$ |
|:---:|:---:|:--------------:|
| F   | F   | V |
| F   | V   | V |
| V   | F   | F |
| V   | V   | V |

::: {.bloc .rem}

<span class="bloc-titre">Remarque : </span><br>

- Les deux tables précédentes coïncident en tous points, les deux fonctions sont alors égales ; ainsi, considérer $P \Longrightarrow Q$ et « non $P$ ou $Q$ » est équivalent. Cela est indispensable à comprendre afin de mieux assimiler le raisonnement par l'absurde et la récurrence.  
- La table de vérité de l'implication justifie la terminologie **Si** $P$ **alors** $Q$. En effet : supposer $P$, c'est dire que $P$ est vraie ; ainsi l'assertion ne peut être vraie que si $Q$ est vraie.
:::

::: {.bloc .ex}

<span class="bloc-titre">Exemple : </span><br>

- On considère $P$ la proposition « $x>5$ » et $Q$ la proposition « $x\geqslant -2$ ».

  1. On a bien $P \Longrightarrow Q$. En effet, « non $P$ ou $Q$ », c'est-à-dire « $x\leqslant 5$ ou $x\geqslant -2$ » est une proposition vraie (on a bien $x\in\R$).  
  2. La proposition $Q \Longrightarrow P$ est fausse. En effet, il suffit par exemple de considérer $x=0$. Une proposition et sa réciproque n'ont pas nécessairement la même valeur de vérité.

- Si $x=3$ alors $x\leqslant 3$. Cette proposition est vraie.
:::

::: {.bloc .rem}

<span class="bloc-titre">Remarque : </span><br>
Pour démontrer $(P \Longrightarrow Q)$, il existe plusieurs méthodes. Ce sont les différents modes de raisonnement en mathématiques.
:::


### Les quantificateurs

#### Notations
::: {.bloc .rem}

<span class="bloc-titre">Remarque : </span><br>
Lorsqu'une proposition dépend d'un paramètre, on peut utiliser deux types de quantificateurs :

- Un quantificateur existentiel « il existe » : $\exists$ ;  
- Un quantificateur universel « pour tout » : $\forall$.
:::

::: {.bloc .ex}

<span class="bloc-titre">Exemple : </span><br>
On considère une proposition mathématique dépendant d'un objet mathématique $x$ quelconque : un réel, un point, une fonction, ...

1. La proposition $\exists x,\, P(x)$  
   Signifie que l'on peut trouver un objet $x$ tel que la proposition $P(x)$ soit vraie.

   - $\exists x\in\R$, $x^2=1$.  
   - En notant $\mathscr{P}$ le plan, on a la proposition suivante :  
     $\forall A,B\in\mathscr{P}$, $A \neq B$, $\exists M\in\mathscr{P}$, $AM=BM$.

2. La proposition $\forall x,\, P(x)$  
   Signifie que pour tout objet $x$, la proposition sera vérifiée.

   - $\forall x\in\R$, $x^2\geqslant 0$.  
   - En notant $\mathscr{P}$ le plan, on a la proposition suivante :  
     $\forall M\in\mathscr{C}(O;r)$, $OM=r$ ;  
   - $\forall A,B\in\mathscr{P}$, $A\neq B$, $\exists M\in\mathscr{P}$, $AM=BM$.
:::

#### Négation
On considère la proposition suivante :  
« *En vacances, il a fait beau tous les jours* ».  
Cette phrase possède un quantificateur universel : « tous les ».  
La négation est :  
« *En vacances, il y a au moins un jour où il n'a pas fait beau.* »

::: {.bloc .thm}

<span class="bloc-titre">Théorème (admis) : </span><br>
Soit $P(x)$ une proposition dépendant de $x$, alors :

- La négation de $\forall x,\, P(x)$ est $\exists x$, non $P(x)$.  
- La négation de $\exists x,\, P(x)$ est $\forall x$, non $P(x)$.
:::

::: {.bloc .ex}

<span class="bloc-titre">Exemple : </span><br>
On considère la phrase suivante :  
$$\forall x\in I,\, \exists k\in\R,\, f(x)=k$$

1. **Traduction.** Cette phrase signifie que pour tout réel $x$ de $I$, l'image de $x$ par $f$ existe : $f$ est définie sur $I$.  
2. **Négation.** $\exists x\in I,\, \forall k\in\R,\, f(x)\neq k$. Autrement dit, $f$ n'est pas définie en au moins un point de $I$ (donc pas sur tout $I$).
:::

#### Place des quantificateurs
::: {.bloc .ex}

<span class="bloc-titre">Exemple : </span><br>

- Proposition :  
  $$\forall x\in\R,\, \forall y\in\R,\ (x+y)^2=x^2+y^2+2xy.$$  
  Ici l'ordre des quantificateurs peut être inversé sans changer le sens.

- Proposition :  
  $$\exists x\in\R,\, \exists y\in\R^+,\ x^2=y.$$  
  Ici, $y$ dépend du choix de $x$ : prendre comme valeur de $y$ le carré de $x$.  
  Si on inverse :  
  $$\exists y\in\R^+,\, \exists x\in\R,\ x^2=y,$$  
  c'est $x$ qui dépend de $y$ : tout nombre positif admet au moins un antécédent par la fonction carré.

- On considère :  
  $$ \forall x\in\R,\, \exists y\in\R,\, f(x)=y \quad \text{et} \quad
  \exists y\in\R,\, \forall x\in\R,\, f(x)=y.$$  
  Ces deux phrases n'ont pas le même sens.

  - La première signifie que $f$ est définie sur $\R$ (le choix de $y$ dépend de $x$).  
  - La seconde signifie que $f$ est constante sur $\R$ (le choix de $y$ est indépendant de $x$).
:::

::: {.bloc .rem}

<span class="bloc-titre">Remarque : </span><br>
Dans ce dernier exemple, on peut remarquer que  
$$(\exists y\in\R,\, \forall x\in\R,\, f(x)=y)\ \Longrightarrow\
(\forall x\in\R,\, \exists y\in\R,\, f(x)=y).$$  
De façon générale, on a toujours :  
$$(\exists y,\, \forall x,\, P(x;y)) \Longrightarrow (\forall x,\, \exists y,\, P(x;y)).$$
:::


<div class="nav-pages">
  <a class="prev" href="proposition.html">⬅️</a>
  <a class="next" href="deduction_contreExemple.html">➡️</a>
</div>
